#server:
#  ssl:
#    enabled: true
#    key-store: classpath:/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 1234

spring:
  datasource:
    url: jdbc:mariadb://52.78.101.95:5010/test
    username: root
    password: S10P12A409

  kafka:
    bootstrap-servers: 52.78.101.95:9092
    consumer:
      bootstrap-servers: 52.78.101.95:9092
      group-id: board-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.26.5.31:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

domain: https://dear103.store
