spring:
  datasource:
    url: jdbc:mariadb://52.79.143.176:5040/test
    username: testuser
    password: 1234

  kafka:
    bootstrap-servers: 172.26.5.31:9092
    consumer:
      bootstrap-servers: 172.26.5.31:9092
      group-id: board-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.26.5.31:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

domain: https://lightswitch.kr/test/

logging:
  level:
    root: info
