server:
  port: 7040

spring:
  profiles:
    active: deploy
  jpa:
    hibernate:
      ddl-auto: update

  # redis 설정
  data:
    redis:
      host: 52.78.101.95
      port: 6379
      password: switchlight2024!
